<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="IServices\**" />
    <EmbeddedResource Remove="IServices\**" />
    <None Remove="IServices\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JoinTogether.DAL\JoinTogether.DAL.csproj" />
    <ProjectReference Include="..\JoinTogether.Shared\JoinTogether.Shared.csproj" />
  </ItemGroup>

</Project>
