name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore JoinTogether.API.slnx

      - name: Build
        run: dotnet build JoinTogether.API.slnx --no-restore --configuration Release

      - name: Run tests
        run: dotnet test JoinTogether.API.slnx --no-build --configuration Release --verbosity normal
